version: "3.8"

services: 
    sqlserver:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server
        ports: 
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=yourStrongPassword12#
        volumes: 
            - sqldata:/var/opt/mssql
    web-app:
        container_name: web-app
        build:
            dockerfile: ./TaskBoard.WebApp/Dockerfile
        ports: 
            - "5000:80"
        restart: on-failure

volumes:
    sqldata: