global:
  scrape_interval: 15s

rule_files:
  - alert-rules-contact-book.yaml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: "contact-book"
    static_configs:
      - targets: ["localhost:8080"]
