version: "3"
services:
  app:
    image: kaiserdmc/student-registry-jenkins:latest
    ports:
      - "8080:8080" # Map port 3030 on the host to port 3030 in the container
    environment:
      - NODE_ENV=production
